# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-11 16:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userswitchsetting',
            unique_together=set([('user', 'setting')]),
        ),
        migrations.AlterUniqueTogether(
            name='uservisibilitysetting',
            unique_together=set([('user', 'setting')]),
        ),
    ]
