EVENT_PUSH = 'push'
EVENT_BRANCH = 'branch'
EVENT_TAG = 'tag'
EVENT_COMMIT_COMMENT = 'commit_comment'
EVENT_PULL_REQUEST = 'pull_request'
EVENT_PULL_REQUEST_COMMENT = 'pull_request_comment'
EVENT_ISSUE = 'issue'
EVENT_ISSUE_COMMENT = 'issue_comment'
EVENT_WIKI = 'wiki'
EVENT_RELEASE = 'release'

EVENT_COMMUNICATION = 'communication'
EVENT_PROGRESS = 'progress'
EVENT_APPLICATION = 'application'

ACTION_CREATED = 'created'
ACTION_DELETED = 'deleted'
ACTION_EDITED = 'edited'
ACTION_UPDATED = 'updated'
ACTION_OPENED = 'opened'
ACTION_CLOSED = 'closed'
ACTION_MERGED = 'merged'
ACTION_REOPENED = 'reopened'
ACTION_PUBLISHED = 'published'

ACTIVITY_INTEGRATION = 'integration'
ACTIVITY_EVENT = 'event'
ACTIVITY_EVENT_ID = 'event_id'
ACTIVITY_ACTION = 'action'
ACTIVITY_URL = 'url'
ACTIVITY_REF = 'ref'
ACTIVITY_REF_NAME = 'ref_name'
ACTIVITY_AVATAR_URL = 'avatar_url'
ACTIVITY_USERNAME = 'username'
ACTIVITY_FULLNAME = 'fullname'
ACTIVITY_TITLE = 'title'
ACTIVITY_BODY = 'body'
ACTIVITY_CREATED_AT = 'created_at'
