# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-13 23:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tunga_profiles', '0027_auto_20170611_1811'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillPage',
            fields=[
                ('keyword', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('welcome_header', models.CharField(max_length=50)),
                ('welcome_sub_header', models.CharField(max_length=100)),
                ('welcome_cta', models.CharField(max_length=30)),
                ('pitch_header', models.CharField(max_length=80)),
                ('pitch_body', models.TextField()),
                ('story_header', models.CharField(max_length=80)),
                ('story_body', models.TextField()),
                ('story_image', models.ImageField(blank=True, null=True, upload_to='pages/uploads/%Y/%m/%d')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tunga_profiles.Skill')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SkillPageProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro', models.CharField(max_length=100)),
                ('priority', models.IntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_profiles_created', to=settings.AUTH_USER_MODEL)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tunga_pages.SkillPage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='skillpageprofile',
            unique_together=set([('user', 'page')]),
        ),
    ]
