# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-14 00:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_pages', '0002_auto_20170713_2328'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skillpageprofile',
            options={'ordering': ['-priority', '-created_at'], 'verbose_name': 'skill page profile'},
        ),
    ]
