# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-23 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_pages', '0004_auto_20170717_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillpage',
            name='story_interlude_one_text',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='skillpage',
            name='story_interlude_two_text',
            field=models.CharField(max_length=200),
        ),
    ]
