# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-26 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_pages', '0007_auto_20170724_0550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillpage',
            name='welcome_sub_header',
            field=models.CharField(max_length=100),
        ),
    ]
