# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-26 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_pages', '0010_auto_20170726_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillpage',
            name='welcome_cta',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='skillpage',
            name='welcome_header',
            field=models.CharField(max_length=70),
        ),
    ]
