# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-26 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_pages', '0011_auto_20170726_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillpage',
            name='pitch_header',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='skillpage',
            name='story_header',
            field=models.CharField(max_length=100),
        ),
    ]
