# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-29 23:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_tasks', '0002_task_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
