# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-01 05:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_tasks', '0003_auto_20160429_2315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assignee',
        ),
        migrations.AddField(
            model_name='participation',
            name='assignee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participation',
            name='role',
            field=models.CharField(default='Developer', max_length=100),
        ),
    ]
