# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-12 18:56
from __future__ import unicode_literals

from django.db import migrations
import tagulous.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_tasks', '0004_auto_20160501_0549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='skills',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, blank=True, help_text='Enter a comma-separated tag string', initial='Makerere University', to='tunga_profiles.Skill'),
        ),
    ]
