# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_tasks', '0005_auto_20160512_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskrequest',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Close Request'), (2, 'Payment Request')], help_text='1 - Close Request,2 - Payment Request'),
        ),
    ]
