# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_tasks', '0006_auto_20160522_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='visible_to',
        ),
        migrations.AddField(
            model_name='application',
            name='deliver_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='pitch',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='can_apply',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='task',
            name='update_schedule',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Hourly'), (2, 'Daily'), (3, 'Weekly'), (4, 'Monthly'), (5, 'Quaterly'), (6, 'Annually')], null=True),
        ),
    ]
