# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 20:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_tasks', '0007_auto_20160525_1953'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='can_apply',
            new_name='apply',
        ),
    ]
