# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_tasks', '0009_task_apply_closed_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='update_schedule',
        ),
        migrations.AddField(
            model_name='task',
            name='update_interval',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='update_interval_units',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Hourly'), (2, 'Daily'), (3, 'Weekly'), (4, 'Monthly'), (5, 'Quarterly'), (6, 'Annually')], null=True),
        ),
    ]
