# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_tasks', '0011_auto_20160527_0616'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='hours_available',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='hours_needed',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
