# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-23 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_tasks', '0014_auto_20160623_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressevent',
            name='last_reminder_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
