# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-26 17:56
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_tasks', '0015_progressevent_last_reminder_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='progressreport',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tunga_tasks.ProgressEvent'),
        ),
        migrations.AlterField(
            model_name='progressreport',
            name='percentage',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
