# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-07 14:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tunga_tasks', '0016_auto_20160626_1756'),
    ]

    operations = [
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[(b'google', b'Google'), (b'bitbucket_oauth2', b'Bitbucket'), (b'twitter', b'Twitter'), (b'gitlab', b'GitLab'), (b'github', b'GitHub'), (b'facebook', b'Facebook'), (b'linkedin_oauth2', b'LinkedIn')], max_length=30)),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Repo'), (2, 'Issue')], help_text='1 - Repo,2 - Issue')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='integrations_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='IntegrationEvent',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='integration_events_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id', 'name'],
            },
        ),
        migrations.CreateModel(
            name='IntegrationMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_key', models.CharField(max_length=30)),
                ('meta_value', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='integration_meta_created', to=settings.AUTH_USER_MODEL)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tunga_tasks.Integration')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='integration',
            name='events',
            field=models.ManyToManyField(related_name='integrations', to='tunga_tasks.IntegrationEvent'),
        ),
        migrations.AddField(
            model_name='integration',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tunga_tasks.Task'),
        ),
        migrations.AlterUniqueTogether(
            name='integration',
            unique_together=set([('task', 'provider')]),
        ),
    ]
