# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-08 11:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_tasks', '0017_auto_20160707_1407'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(blank=True, max_length=30, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('ref', models.CharField(blank=True, max_length=30, null=True)),
                ('ref_name', models.CharField(blank=True, max_length=50, null=True)),
                ('username', models.CharField(blank=True, max_length=30, null=True)),
                ('fullname', models.CharField(blank=True, max_length=50, null=True)),
                ('avatar_url', models.URLField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integration_activities', to='tunga_tasks.IntegrationEvent')),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='tunga_tasks.Integration')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
