# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-10 00:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.crypto


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_tasks', '0018_integrationactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='integration',
            name='secret',
            field=models.CharField(default=django.utils.crypto.get_random_string, max_length=30),
        ),
    ]
