# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-11 13:26
from __future__ import unicode_literals

from django.db import migrations, models
import tunga_utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_tasks', '0019_integration_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='btc_address',
            field=models.CharField(blank=True, max_length=40, null=True, validators=[tunga_utils.validators.validate_btc_address]),
        ),
        migrations.AddField(
            model_name='task',
            name='invoice_amount',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='fee',
            field=models.DecimalField(decimal_places=4, max_digits=19),
        ),
    ]
