# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 01:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_tasks', '0020_auto_20160711_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('bitonic', 'Pay with ideal / mister cash'), ('bitcoin', 'Pay with bitcoin'), ('bank', 'Pay by bank transfer')], help_text='bitonic - Pay with ideal / mister cash,bitcoin - Pay with bitcoin,bank - Pay by bank transfer', max_length=30, null=True),
        ),
    ]
