# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 02:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_tasks', '0021_task_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='btc_paid',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='participation',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participation',
            name='paid_to',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='participation',
            name='paid_with',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='pay_distributed',
            field=models.BooleanField(default=False),
        ),
    ]
