# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_tasks', '0023_task_invoice_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participation',
            name='btc_paid',
        ),
        migrations.AddField(
            model_name='participation',
            name='btc_received',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='task',
            name='btc_received',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=10),
        ),
    ]
