# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_tasks', '0025_auto_20160718_1124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participation',
            name='btc_received',
        ),
        migrations.RemoveField(
            model_name='participation',
            name='paid_to',
        ),
        migrations.RemoveField(
            model_name='participation',
            name='paid_with',
        ),
        migrations.AddField(
            model_name='participation',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='participantpayment',
            name='btc_sent',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='participantpayment',
            unique_together=set([('participant', 'source')]),
        ),
    ]
