# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_tasks', '0026_auto_20160719_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participation',
            name='share',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
