# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-24 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_tasks', '0027_auto_20160719_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='btc_price',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True),
        ),
    ]
