# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_tasks', '0028_auto_20160724_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantpayment',
            name='btc_received',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='participantpayment',
            name='btc_sent',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='taskpayment',
            name='btc_price',
            field=models.DecimalField(decimal_places=8, max_digits=18),
        ),
        migrations.AlterField(
            model_name='taskpayment',
            name='btc_received',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=18),
        ),
    ]
