# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-04 06:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_tasks', '0030_taskinvoice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskinvoice',
            old_name='invoice_number',
            new_name='number',
        ),
    ]
