# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-05 23:18
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_tasks', '0031_auto_20160804_0655'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantpayment',
            name='idem_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
