# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-06 00:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_tasks', '0032_participantpayment_idem_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskinvoice',
            name='payment_method',
            field=models.CharField(choices=[('bitonic', 'Pay with ideal / mister cash'), ('bitcoin', 'Pay with bitcoin'), ('bank', 'Pay by bank transfer')], default='bitcoin', help_text='bitonic - Pay with ideal / mister cash,bitcoin - Pay with bitcoin,bank - Pay by bank transfer', max_length=30),
            preserve_default=False,
        ),
    ]
