# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-23 10:24
from __future__ import unicode_literals

from django.db import migrations, models
import tunga_utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_tasks', '0035_auto_20160920_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantpayment',
            name='extra',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='participantpayment',
            name='destination',
            field=models.CharField(blank=True, max_length=40, null=True, validators=[tunga_utils.validators.validate_btc_address]),
        ),
        migrations.AlterField(
            model_name='participantpayment',
            name='ref',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='participantpayment',
            name='status',
            field=models.CharField(choices=[(b'pending', 'Pending'), (b'initiated', 'Initiated'), (b'processing', 'Processing'), (b'completed', 'Completed'), (b'failed', 'Failed')], default=b'pending', help_text='pending - Pending, initiated - Initiated, processing - Processing, completed - Completed, failed - Failed', max_length=30),
        ),
    ]
