# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-25 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_tasks', '0036_auto_20160923_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='provider',
            field=models.CharField(choices=[(b'google', b'Google'), (b'slack', b'Slack'), (b'bitbucket_oauth2', b'Bitbucket'), (b'twitter', b'Twitter'), (b'gitlab', b'GitLab'), (b'github', b'GitHub'), (b'facebook', b'Facebook'), (b'linkedin_oauth2', b'LinkedIn')], max_length=30),
        ),
        migrations.AlterField(
            model_name='integration',
            name='type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Repo'), (2, 'Issue')], help_text='1 - Repo,2 - Issue', null=True),
        ),
    ]
