# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-22 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_tasks', '0037_auto_20160925_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='provider',
            field=models.CharField(choices=[(b'github', 'GitHub'), (b'slack', 'Slack'), (b'harvest', 'Harvest')], help_text='github - GitHub,slack - Slack,harvest - Harvest', max_length=30),
        ),
    ]
