# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-18 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_tasks', '0039_progressreport_obstacles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrationmeta',
            name='meta_value',
            field=models.CharField(max_length=500),
        ),
    ]
