# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-19 05:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_tasks', '0041_task_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_project',
            field=models.BooleanField(default=False),
        ),
    ]
