# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-29 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_tasks', '0044_auto_20170128_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='coders_needed',
            field=models.IntegerField(blank=True, choices=[(1, 'One coder'), (-1, 'Multiple coders')], null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='type',
            field=models.IntegerField(blank=True, choices=[(1, 'Web'), (2, 'Mobile'), (3, 'Other')], null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='apply',
            field=models.BooleanField(default=True, help_text='True if developers can apply for this task (visibility can override this)'),
        ),
        migrations.AlterField(
            model_name='task',
            name='closed',
            field=models.BooleanField(default=False, help_text='True if the task is closed'),
        ),
        migrations.AlterField(
            model_name='task',
            name='is_project',
            field=models.BooleanField(default=False, help_text='True if task will be broken into sub-tasks'),
        ),
        migrations.AlterField(
            model_name='task',
            name='paid',
            field=models.BooleanField(default=False, help_text='True if the task is paid'),
        ),
    ]
