# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-30 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_tasks', '0045_auto_20170129_0728'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='billing_method',
            field=models.IntegerField(blank=True, choices=[(1, 'Fixed'), (2, 'Hourly')], default=1, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='deliverables',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='has_requirements',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='pm_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='scope',
            field=models.IntegerField(blank=True, choices=[(1, 'One-time'), (2, 'Ongoing')], null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='stack_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
