# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-01 04:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_tasks', '0047_auto_20170130_0628'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='skype_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
