# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-05 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_tasks', '0050_auto_20170201_0659'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='pay_distributed',
            field=models.BooleanField(default=False, help_text='True if task has been paid and entire payment has been distributed tp participating developers'),
        ),
        migrations.AlterField(
            model_name='task',
            name='satisfaction',
            field=models.SmallIntegerField(blank=True, help_text="Client's rating of task developers", null=True),
        ),
    ]
