# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-27 01:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_tasks', '0052_task_contact_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='scope',
            field=models.IntegerField(blank=True, choices=[(1, 'Task'), (3, 'Project'), (2, 'Ongoing')], null=True),
        ),
    ]
