# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-03 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_tasks', '0054_auto_20170227_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='scope',
            field=models.IntegerField(choices=[(1, 'Task'), (3, 'Project'), (2, 'Ongoing')], default=1),
            preserve_default=False,
        ),
    ]
