# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-03 17:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_tasks', '0056_auto_20170303_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='is_project',
        ),
    ]
