# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-04 04:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_tasks', '0057_remove_task_is_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='source',
            field=models.IntegerField(choices=[(1, 'Default'), (2, 'New User')], default=1),
        ),
    ]
