# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-04 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_tasks', '0058_task_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='source',
            field=models.IntegerField(choices=[(1, 'Default'), (2, 'New Wizard User')], default=1),
        ),
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.IntegerField(choices=[(1, 'Web'), (2, 'Mobile'), (3, 'Other')], default=3),
            preserve_default=False,
        ),
    ]
