# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-18 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_tasks', '0060_auto_20170304_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progressevent',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Update'), (2, 'Periodic Update'), (3, 'Milestone'), (4, 'Final Draft'), (5, 'Submission')], default=1, help_text='1 - Update,2 - Periodic Update,3 - Milestone,4 - Final Draft,5 - Submission'),
        ),
    ]
