# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-06 23:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tunga_tasks', '0061_auto_20170306_1946'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introduction', models.TextField()),
                ('status', models.CharField(choices=[(b'initial', 'Initial'), (b'pending', 'Pending'), (b'approved', 'Approved'), (b'declined', 'Declined'), (b'accepted', 'Accepted'), (b'rejected', 'Rejected')], default=b'initial', help_text='initial - Initial, pending - Pending, approved - Approved, declined - Declined, accepted - Accepted, rejected - Rejected', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('moderated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='estimates_moderated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introduction', models.TextField()),
                ('in_scope', models.TextField()),
                ('out_scope', models.TextField()),
                ('assumptions', models.TextField()),
                ('deliverables', models.TextField()),
                ('architecture', models.TextField()),
                ('technology', models.TextField()),
                ('process', models.TextField()),
                ('reporting', models.TextField()),
                ('status', models.CharField(choices=[(b'initial', 'Initial'), (b'pending', 'Pending'), (b'approved', 'Approved'), (b'declined', 'Declined'), (b'accepted', 'Accepted'), (b'rejected', 'Rejected')], default=b'initial', help_text='initial - Initial, pending - Pending, approved - Approved, declined - Declined, accepted - Accepted, rejected - Rejected', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('moderated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='quotes_moderated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='pm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tasks_managed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quote',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tunga_tasks.Task'),
        ),
        migrations.AddField(
            model_name='quote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='estimate',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tunga_tasks.Task'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
