# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-07 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_tasks', '0062_auto_20170306_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='moderated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='moderated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='status',
            field=models.CharField(choices=[(b'initial', 'Initial'), (b'submitted', 'Submitted'), (b'approved', 'Approved'), (b'declined', 'Declined'), (b'accepted', 'Accepted'), (b'rejected', 'Rejected')], default=b'initial', help_text='initial - Initial, submitted - Submitted, approved - Approved, declined - Declined, accepted - Accepted, rejected - Rejected', max_length=30),
        ),
        migrations.AlterField(
            model_name='quote',
            name='status',
            field=models.CharField(choices=[(b'initial', 'Initial'), (b'submitted', 'Submitted'), (b'approved', 'Approved'), (b'declined', 'Declined'), (b'accepted', 'Accepted'), (b'rejected', 'Rejected')], default=b'initial', help_text='initial - Initial, submitted - Submitted, approved - Approved, declined - Declined, accepted - Accepted, rejected - Rejected', max_length=30),
        ),
    ]
