# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-10 11:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_tasks', '0066_auto_20170309_1656'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='task',
            unique_together=set([]),
        ),
    ]
