# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-10 16:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tunga_tasks', '0067_auto_20170310_1119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estimate',
            old_name='responded_at',
            new_name='reviewed_at',
        ),
        migrations.AddField(
            model_name='estimate',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='estimates_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quote',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='quotes_reviewed', to=settings.AUTH_USER_MODEL),
        ),
    ]
