# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_tasks', '0070_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='approved',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
