# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_tasks', '0071_task_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
