# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_tasks', '0072_auto_20170319_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='complete_task_email_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='reminded_complete_task',
            field=models.BooleanField(default=False),
        ),
    ]
