# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_tasks', '0074_task_check_task_email_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='bid',
            field=models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=19, null=True),
        ),
    ]
