# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_tasks', '0075_task_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='moderator_email_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estimate',
            name='reviewed_email_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estimate',
            name='reviewer_email_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='moderator_email_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='reviewed_email_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='reviewer_email_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
