# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 04:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_tasks', '0076_auto_20170321_0600'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='days_available',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
