# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_tasks', '0079_auto_20170324_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='pm_time_percentage',
            field=models.DecimalField(decimal_places=4, default=15, max_digits=7),
        ),
        migrations.AlterField(
            model_name='task',
            name='tunga_percentage_dev',
            field=models.DecimalField(decimal_places=4, default=34.21, max_digits=7),
        ),
        migrations.AlterField(
            model_name='task',
            name='tunga_percentage_pm',
            field=models.DecimalField(decimal_places=4, default=48.71, max_digits=7),
        ),
    ]
