# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 05:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_tasks', '0081_auto_20170330_0603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progressreport',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tunga_tasks.ProgressEvent'),
        ),
    ]
