# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 03:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_tasks', '0082_auto_20170410_0547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progressevent',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Update'), (2, 'Periodic Update'), (3, 'Milestone'), (4, 'Final Draft'), (5, 'Submission'), (6, 'PM Update')], default=1, help_text='1 - Update,2 - Periodic Update,3 - Milestone,4 - Final Draft,5 - Submission,6 - PM Update'),
        ),
    ]
