# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_tasks', '0083_auto_20170413_0334'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressreport',
            name='deadline_report',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='progressreport',
            name='last_deadline_met',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='progressreport',
            name='next_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='progressreport',
            name='team_appraisal',
            field=models.TextField(blank=True, null=True),
        ),
    ]
