# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-16 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_tasks', '0084_auto_20170413_0705'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='review',
            field=models.BooleanField(default=False, help_text='True if task or project should be reviewed by an admin'),
        ),
        migrations.AlterField(
            model_name='task',
            name='approved',
            field=models.BooleanField(default=False, help_text='True if task or project is ready for developers'),
        ),
        migrations.AlterField(
            model_name='task',
            name='contact_required',
            field=models.BooleanField(default=False, help_text='True if client chooses to be contacted for more info?'),
        ),
        migrations.AlterField(
            model_name='task',
            name='pay_distributed',
            field=models.BooleanField(default=False, help_text='True if task has been paid and entire payment has been distributed to participating developers'),
        ),
    ]
