# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-26 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_tasks', '0085_auto_20170416_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='google_drive_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='trello_board_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
