# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-27 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_tasks', '0085_auto_20170416_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='schedule_call_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='schedule_call_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
