# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-30 10:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_tasks', '0086_auto_20170426_1231'),
        ('tunga_tasks', '0087_auto_20170429_1107'),
    ]

    operations = [
    ]
