# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-07 09:53
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_tasks', '0088_merge_20170430_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='edit_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
