# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-08 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_tasks', '0089_task_edit_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='hubspot_deal_id',
            field=models.IntegerField(editable=False, null=True),
        ),
    ]
