# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-11 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_tasks', '0092_task_analytics_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='analytics_id',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
