# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-12 10:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_tasks', '0091_auto_20170510_1055'),
        ('tunga_tasks', '0093_auto_20170511_0649'),
    ]

    operations = [
    ]
