# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-19 19:30
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_tasks', '0093_auto_20170511_0649'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressreport',
            name='rate_communication',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='progressreport',
            name='rate_deliverables',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='progressevent',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Update'), (2, 'Periodic Update'), (3, 'Milestone'), (4, 'Final Draft'), (5, 'Submission'), (6, 'PM Update'), (7, 'Client Survey')], default=1, help_text='1 - Update,2 - Periodic Update,3 - Milestone,4 - Final Draft,5 - Submission,6 - PM Update,7 - Client Survey'),
        ),
        migrations.AlterField(
            model_name='progressreport',
            name='accomplished',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='progressreport',
            name='percentage',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='progressreport',
            name='status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'On schedule'), (2, 'Behind'), (3, 'Stuck')], help_text='1 - On schedule,2 - Behind,3 - Stuck', null=True),
        ),
    ]
