# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-13 22:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_tasks', '0094_merge_20170512_1004'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MultiTaskPayment',
            new_name='MultiTaskPaymentKey',
        ),
    ]
