# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-26 09:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_tasks', '0097_auto_20170523_0037'),
        ('tunga_tasks', '0095_auto_20170513_2202'),
    ]

    operations = [
    ]
