# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-27 04:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_tasks', '0098_auto_20170526_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskpayment',
            name='currency',
            field=models.CharField(blank=True, choices=[(b'EUR', 'EUR'), (b'USD', 'USD')], max_length=5, null=True),
        ),
    ]
