# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-27 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_tasks', '0099_auto_20170527_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressreport',
            name='deliverable_satisfaction',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='progressreport',
            name='pm_communication',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='progressreport',
            name='pm_deadline_informed',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='progressreport',
            name='this_week_deadline_met',
            field=models.NullBooleanField(),
        ),
    ]
