# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-27 09:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_tasks', '0099_auto_20170527_0407'),
        ('tunga_tasks', '0100_auto_20170527_1204'),
    ]

    operations = [
    ]
