# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-31 02:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tunga_tasks', '0101_merge_20170527_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskinvoice',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='invoices_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='progressreport',
            name='status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'On schedule'), (2, 'Behind'), (3, 'Stuck'), (4, 'Behind but Progressing'), (5, 'Behind and Stuck')], help_text='1 - On schedule,2 - Behind,3 - Stuck,4 - Behind but Progressing,5 - Behind and Stuck', null=True),
        ),
    ]
