# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-02 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_tasks', '0103_progressreport_next_deadline_fail_reason'),
    ]

    operations = [
        migrations.RenameField(
            model_name='progressreport',
            old_name='pm_deadline_informed',
            new_name='deadline_miss_communicated',
        ),
        migrations.RemoveField(
            model_name='progressreport',
            name='deadline_deliverable_rate',
        ),
        migrations.RemoveField(
            model_name='progressreport',
            name='this_week_deadline_met',
        ),
        migrations.AlterField(
            model_name='progressreport',
            name='stuck_reason',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Resolving an Error'), (2, 'Poor Documenatation'), (3, 'Hardware problem'), (4, 'Unclear specifications'), (5, 'Personal Circumstances'), (6, 'Other')], help_text='1 - Resolving an Error,2 - Poor Documenatation,3 - Hardware problem,4 - Unclear specifications,5 - Personal Circumstances,6 - Other', null=True),
        ),
    ]
