# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-02 18:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_tasks', '0104_auto_20170602_1801'),
    ]

    operations = [
        migrations.RenameField(
            model_name='progressreport',
            old_name='next_steps',
            new_name='todo',
        ),
        migrations.RemoveField(
            model_name='progressreport',
            name='today_to_dos',
        ),
    ]
