# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-12 03:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_tasks', '0105_auto_20170602_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tunga_tasks.Task'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tunga_tasks.Task'),
        ),
    ]
