# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-18 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_tasks', '0109_taskinvoice_withhold_tunga_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='call_required',
            field=models.NullBooleanField(help_text='True if client chooses to be called'),
        ),
    ]
