# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-17 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_tasks', '0109_taskinvoice_withhold_tunga_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='slack_admin_token',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
