# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-29 07:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_tasks', '0110_task_call_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='update_interval',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='task',
            name='update_interval_units',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Hour'), (2, 'Day'), (3, 'Week'), (4, 'Month'), (5, 'Quarter'), (6, 'Annual')], default=2),
        ),
    ]
