# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-23 16:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_tasks', '0110_task_call_required'),
        ('tunga_tasks', '0110_task_slack_admin_token'),
    ]

    operations = [
    ]
