# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-26 02:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_tasks', '0111_merge_20170626_0220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='slack_admin_token',
        ),
    ]
