# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-29 14:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_tasks', '0111_auto_20170629_0737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='multi_task_payment',
        ),
        migrations.AddField(
            model_name='multitaskpaymentkey',
            name='btc_price',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='multitaskpaymentkey',
            name='currency',
            field=models.CharField(choices=[(b'EUR', 'EUR'), (b'USD', 'USD')], default=b'EUR', max_length=5),
        ),
        migrations.AddField(
            model_name='multitaskpaymentkey',
            name='fee',
            field=models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='multitaskpaymentkey',
            name='paid',
            field=models.BooleanField(default=False, help_text='True if the task is paid'),
        ),
        migrations.AddField(
            model_name='multitaskpaymentkey',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='multitaskpaymentkey',
            name='payment_method',
            field=models.CharField(blank=True, choices=[(b'stripe', 'Pay with Stripe'), (b'bitonic', 'Pay with iDeal / mister cash'), (b'bitcoin', 'Pay with BitCoin'), (b'bank', 'Pay by bank transfer')], help_text='stripe - Pay with Stripe,bitonic - Pay with iDeal / mister cash,bitcoin - Pay with BitCoin,bank - Pay by bank transfer', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='multi_pay_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tasks', to='tunga_tasks.MultiTaskPaymentKey'),
        ),
        migrations.AddField(
            model_name='taskpayment',
            name='multi_pay_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tunga_tasks.MultiTaskPaymentKey'),
        ),
        migrations.AlterField(
            model_name='taskpayment',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tunga_tasks.Task'),
        ),
    ]
