# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-03 08:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_tasks', '0112_auto_20170629_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='multi_pay_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='multi_tasks', to='tunga_tasks.MultiTaskPaymentKey'),
        ),
    ]
