# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-10 08:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_tasks', '0113_auto_20170703_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='multitaskpaymentkey',
            name='withhold_tunga_fee',
            field=models.BooleanField(default=False, help_text='Only participant portion will be paid if True, and all money paid will be distributed to participants'),
        ),
        migrations.AlterField(
            model_name='task',
            name='multi_pay_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tasks', to='tunga_tasks.MultiTaskPaymentKey'),
        ),
    ]
