# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-19 18:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_tasks', '0115_auto_20170713_2328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='multitaskpaymentkey',
            old_name='fee',
            new_name='amount',
        ),
    ]
