# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-20 16:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_tasks', '0116_auto_20170719_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskinvoice',
            name='developer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='developer_invoices', to=settings.AUTH_USER_MODEL),
        ),
    ]
