# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-21 03:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_tasks', '0117_auto_20170720_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='multitaskpaymentkey',
            name='distribute_only',
            field=models.BooleanField(default=False, help_text='True if the task is paid'),
        ),
        migrations.AddField(
            model_name='task',
            name='btc_paid',
            field=models.BooleanField(default=False, help_text='True if BTC has been paid in for a Stripe task'),
        ),
        migrations.AddField(
            model_name='task',
            name='btc_paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='multi_pay_distribute_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='distribute_tasks', to='tunga_tasks.MultiTaskPaymentKey'),
        ),
    ]
