# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-25 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_tasks', '0118_auto_20170721_0341'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='withhold_tunga_fee_distribute',
            field=models.BooleanField(default=False, help_text='Only participant portion will be distributed if True, and all money paid will be distributed to participants'),
        ),
    ]
