# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-26 01:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_tasks', '0119_task_withhold_tunga_fee_distribute'),
    ]

    operations = [
        migrations.AddField(
            model_name='multitaskpaymentkey',
            name='processing',
            field=models.BooleanField(default=False, help_text='True if the task is processing'),
        ),
        migrations.AddField(
            model_name='multitaskpaymentkey',
            name='processing_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='processing',
            field=models.BooleanField(default=False, help_text='True if the task is processing'),
        ),
        migrations.AddField(
            model_name='task',
            name='processing_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
