# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-03 07:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_tasks', '0121_remove_multitaskpaymentkey_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='SummaryReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_for', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email_at', models.DateTimeField(auto_now_add=True)),
                ('slack_at', models.DateTimeField(auto_now_add=True)),
                ('developer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dev_summary_reports', to='tunga_tasks.ProgressReport')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner_summary_reports', to='tunga_tasks.ProgressReport')),
                ('pm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pm_summary_reports', to='tunga_tasks.ProgressReport')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tunga_tasks.Task')),
            ],
        ),
    ]
