# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-18 14:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_tasks', '0112_remove_task_slack_admin_token'),
        ('tunga_tasks', '0123_progressevent_missed_notification_at'),
        ('tunga_tasks', '0111_merge_20170623_1612'),
    ]

    operations = [
    ]
