# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-18 00:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_tasks', '0123_progressevent_missed_notification_at'),
        ('tunga_tasks', '0113_merge_20170706_1103'),
    ]

    operations = [
    ]
