# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-18 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_tasks', '0124_merge_20170818_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='last_drip_mail_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
