# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-18 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_tasks', '0125_task_last_drip_mail_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='last_drip_mail',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
