# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-19 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_tasks', '0126_task_last_drip_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='pause_updates_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participation',
            name='updates_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='task',
            name='pause_updates_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
