# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-04 05:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_tasks', '0127_auto_20170819_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='multitaskpaymentkey',
            name='tax_rate',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=19),
        ),
        migrations.AddField(
            model_name='task',
            name='tax_rate',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=19),
        ),
        migrations.AddField(
            model_name='task',
            name='unpaid_balance',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=19),
        ),
        migrations.AddField(
            model_name='taskinvoice',
            name='tax_rate',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=19),
        ),
    ]
