# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-23 13:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_tasks', '0129_auto_20170918_0435'),
        ('tunga_tasks', '0124_merge_20170818_0034'),
    ]

    operations = [
    ]
