# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-23 13:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tunga_tasks', '0130_merge_20170923_1318'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillsApproval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved_with', models.IntegerField(choices=[(1, 'By the Tunga onboarding procedure'), (2, 'A skills testing platform'), (3, 'Has worked on Tunga tasks successfully before')], help_text='1 - By the Tunga onboarding procedure,2 - A skills testing platform,3 - Has worked on Tunga tasks successfully before')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills_approvals', to=settings.AUTH_USER_MODEL)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tunga_tasks.Participation')),
            ],
        ),
    ]
