# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-05 05:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tunga_tasks', '0133_workactivity_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='workactivity',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='assigned_work_activities', to=settings.AUTH_USER_MODEL),
        ),
    ]
