# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-12 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_tasks', '0135_auto_20171011_0120'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='includes_pm_fee',
            field=models.BooleanField(default=False),
        ),
    ]
