# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-13 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_tasks', '0137_auto_20171027_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressreport',
            name='obstacles_prevention',
            field=models.TextField(blank=True, null=True),
        ),
    ]
