# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-15 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_tasks', '0138_progressreport_obstacles_prevention'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantpayment',
            name='btc_price',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='participantpayment',
            name='external_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participantpayment',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
