# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_auth', '0003_tungauser_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='tungauser',
            name='pending',
            field=models.BooleanField(default=True),
        ),
    ]
