# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-01 04:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_auth', '0005_emailvisitor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailvisitor',
            name='last_login_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
