# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-27 03:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_auth', '0006_auto_20170201_0408'),
    ]

    operations = [
        migrations.AddField(
            model_name='tungauser',
            name='source',
            field=models.IntegerField(choices=[(1, 'Default'), (2, 'Task Wizard')], default=1),
        ),
    ]
