# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-18 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_auth', '0007_tungauser_source'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tungauser',
            old_name='last_activity',
            new_name='last_activity_at',
        ),
        migrations.AddField(
            model_name='tungauser',
            name='last_set_password_email_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
