# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-07 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_auth', '0007_tungauser_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tungauser',
            name='type',
            field=models.IntegerField(blank=True, choices=[(1, 'Developer'), (2, 'Project Owner'), (3, 'Project Manager')], null=True),
        ),
    ]
