# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-18 17:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_auth', '0008_auto_20170318_1652'),
        ('tunga_auth', '0008_auto_20170307_1035'),
    ]

    operations = [
    ]
