# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 06:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=20)),
                ('content', models.TextField()),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='0 is the highest order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_pages_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', 'title', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=20, unique=True)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='0 is the highest order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_sections_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', 'title', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='supportpage',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='tunga_support.SupportSection'),
        ),
        migrations.AlterUniqueTogether(
            name='supportpage',
            unique_together=set([('section', 'slug')]),
        ),
    ]
