# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_support', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supportpage',
            options={'ordering': ['order', 'title', '-created_at'], 'verbose_name': 'page', 'verbose_name_plural': 'pages'},
        ),
        migrations.AlterModelOptions(
            name='supportsection',
            options={'ordering': ['order', 'title', '-created_at'], 'verbose_name': 'section', 'verbose_name_plural': 'sections'},
        ),
        migrations.AddField(
            model_name='supportpage',
            name='visibility',
            field=models.CharField(choices=[('all', 'Everyone'), ('developers', 'Developers'), ('project-owners', 'Project Owners')], default='all', help_text='all - Everyone,developers - Developers,project-owners - Project Owners', max_length=20),
        ),
        migrations.AddField(
            model_name='supportsection',
            name='visibility',
            field=models.CharField(choices=[('all', 'Everyone'), ('developers', 'Developers'), ('project-owners', 'Project Owners')], default='all', help_text='all - Everyone,developers - Developers,project-owners - Project Owners', max_length=20),
        ),
        migrations.AlterField(
            model_name='supportpage',
            name='slug',
            field=models.SlugField(help_text='url path for this page (should not include the section slug)', max_length=20),
        ),
        migrations.AlterField(
            model_name='supportsection',
            name='slug',
            field=models.SlugField(help_text='url path for this section', max_length=20, unique=True),
        ),
    ]
