# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-23 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_support', '0002_auto_20160720_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportpage',
            name='visibility',
            field=models.CharField(choices=[('all', 'Everyone'), ('developers', 'Developers'), ('project-owners', 'Project Owners')], default='all', help_text='all - Everyone, developers - Developers, project-owners - Project Owners', max_length=20),
        ),
        migrations.AlterField(
            model_name='supportsection',
            name='visibility',
            field=models.CharField(choices=[('all', 'Everyone'), ('developers', 'Developers'), ('project-owners', 'Project Owners')], default='all', help_text='all - Everyone, developers - Developers, project-owners - Project Owners', max_length=20),
        ),
    ]
