# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-28 08:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_utils', '0003_auto_20160626_1756'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together=set([('content_type', 'object_id', 'criteria', 'created_by')]),
        ),
    ]
