# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-11 00:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_utils', '0004_auto_20160628_0807'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactrequest',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
