# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-11 04:21
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_utils', '0005_contactrequest_email_sent_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='score',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
