# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 11:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_utils', '0008_auto_20161219_0445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
