# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-05 07:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_profiles', '0003_userprofile_phone_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Settings',
        ),
    ]
