# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 18:00
from __future__ import unicode_literals

from django.db import migrations, models
import tunga_utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_profiles', '0004_delete_settings'),
    ]

    operations = [
        #migrations.DeleteModel(
        #    name='Institution',
        #),
        migrations.AlterField(
            model_name='education',
            name='end_month',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Jan'), (2, 'Feb'), (3, 'Mar'), (4, 'Apr'), (5, 'May'), (6, 'Jun'), (7, 'Jul'), (8, 'Aug'), (9, 'Sep'), (10, 'Oct'), (11, 'Nov'), (12, 'Dec')], null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='end_year',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[tunga_utils.validators.validate_year]),
        ),
        migrations.AlterField(
            model_name='education',
            name='institution',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='education',
            name='start_month',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Jan'), (2, 'Feb'), (3, 'Mar'), (4, 'Apr'), (5, 'May'), (6, 'Jun'), (7, 'Jul'), (8, 'Aug'), (9, 'Sep'), (10, 'Oct'), (11, 'Nov'), (12, 'Dec')]),
        ),
        migrations.AlterField(
            model_name='education',
            name='start_year',
            field=models.PositiveIntegerField(validators=[tunga_utils.validators.validate_year]),
        ),
        migrations.AlterField(
            model_name='work',
            name='end_month',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Jan'), (2, 'Feb'), (3, 'Mar'), (4, 'Apr'), (5, 'May'), (6, 'Jun'), (7, 'Jul'), (8, 'Aug'), (9, 'Sep'), (10, 'Oct'), (11, 'Nov'), (12, 'Dec')], null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='end_year',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[tunga_utils.validators.validate_year]),
        ),
        migrations.AlterField(
            model_name='work',
            name='start_month',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Jan'), (2, 'Feb'), (3, 'Mar'), (4, 'Apr'), (5, 'May'), (6, 'Jun'), (7, 'Jul'), (8, 'Aug'), (9, 'Sep'), (10, 'Oct'), (11, 'Nov'), (12, 'Dec')]),
        ),
        migrations.AlterField(
            model_name='work',
            name='start_year',
            field=models.PositiveIntegerField(validators=[tunga_utils.validators.validate_year]),
        ),
    ]
