# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 19:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_profiles', '0005_auto_20160522_1800'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Institution',
        ),
    ]
