# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-03 22:37
from __future__ import unicode_literals

from django.db import migrations, models
import django_countries.fields
import tunga_profiles.validators
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_profiles', '0006_delete_institution'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeveloperApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True, validators=[tunga_profiles.validators.validate_email])),
                ('phone_number', models.CharField(max_length=15)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('city', models.CharField(max_length=50)),
                ('stack', models.TextField()),
                ('experience', models.TextField()),
                ('discovery_story', models.TextField()),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Received'), (1, 'Accepted'), (2, 'Rejected')], default=0, help_text='0 - Received,1 - Accepted,2 - Rejected')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmation_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('confirmation_sent_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
