# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 07:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tunga_profiles', '0009_auto_20160712_1156'),
    ]

    operations = [
        migrations.CreateModel(
            name='BTCWallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('coinbase', 'Coinbase')], help_text='coinbase - Coinbase', max_length=30)),
                ('token', models.TextField(help_text='"oauth_token" (OAuth1) or access token (OAuth2)', verbose_name='token')),
                ('token_secret', models.TextField(blank=True, help_text='"oauth_token_secret" (OAuth1) or refresh token (OAuth2)', verbose_name='token secret')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='expires at')),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'bitcoin wallet',
            },
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='btc_wallet_provider',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='btc_wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tunga_profiles.BTCWallet'),
        ),
        migrations.AlterUniqueTogether(
            name='btcwallet',
            unique_together=set([('user', 'provider')]),
        ),
    ]
