# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-23 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_profiles', '0010_auto_20160713_0737'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='id_document',
            field=models.ImageField(blank=True, null=True, upload_to='ids/%Y/%m/%d'),
        ),
    ]
