# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-03 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_profiles', '0012_auto_20160801_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='company_reg_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
