# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-23 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_profiles', '0015_developernumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='mobile_money_cc',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
