# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-23 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_profiles', '0016_userprofile_mobile_money_cc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='mobile_money_cc',
            field=models.CharField(blank=True, choices=[(b'234', 'Nigeria (+234)'), (b'255', 'Tanzania (+255)'), (b'256', 'Uganda (+256)')], help_text='234 - Nigeria (+234),255 - Tanzania (+255),256 - Uganda (+256)', max_length=5, null=True),
        ),
    ]
