# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-25 14:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tunga_profiles', '0017_auto_20160923_1042'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppIntegration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[(b'slack', 'Slack')], help_text='slack - Slack', max_length=30)),
                ('token', models.TextField(help_text='"oauth_token" (OAuth1) or access token (OAuth2)', verbose_name='token')),
                ('token_secret', models.TextField(blank=True, help_text='"oauth_token_secret" (OAuth1) or refresh token (OAuth2)', verbose_name='token secret')),
                ('extra', models.TextField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='expires at')),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'app integration',
                'verbose_name_plural': 'app integrations',
            },
        ),
        migrations.AlterUniqueTogether(
            name='sociallink',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='sociallink',
            name='platform',
        ),
        migrations.RemoveField(
            model_name='sociallink',
            name='user',
        ),
        migrations.RemoveField(
            model_name='socialplatform',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='SocialLink',
        ),
        migrations.DeleteModel(
            name='SocialPlatform',
        ),
    ]
