# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-22 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_profiles', '0019_auto_20160926_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appintegration',
            name='provider',
            field=models.CharField(choices=[(b'slack', 'Slack'), (b'harvest', 'Harvest')], help_text='slack - Slack,harvest - Harvest', max_length=30),
        ),
    ]
