# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-30 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_profiles', '0021_developerinvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='developerinvitation',
            name='invitation_sent_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
