# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-02 01:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_profiles', '0022_developerinvitation_invitation_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='developerinvitation',
            name='type',
            field=models.IntegerField(choices=[(1, 'Developer'), (3, 'Project Manager')], default=1),
        ),
    ]
