# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-02 03:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_profiles', '0023_developerinvitation_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='developerinvitation',
            options={'verbose_name': 'user invitation'},
        ),
        migrations.AddField(
            model_name='developerinvitation',
            name='resent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='developerinvitation',
            name='resent_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
