# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-09 03:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_profiles', '0024_auto_20170302_0346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developerinvitation',
            name='type',
            field=models.IntegerField(choices=[(1, 'Developer'), (2, 'Project Owner'), (3, 'Project Manager')], default=1),
        ),
    ]
