# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_profiles', '0025_auto_20170309_0306'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='status',
            field=models.CharField(choices=[(b'initial', 'Initial'), (b'accepted', 'Accepted'), (b'rejected', 'Rejected')], default=b'initial', help_text='initial - Initial, accepted - Accepted, rejected - Rejected', max_length=30),
        ),
    ]
