# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-28 06:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_profiles', '0027_auto_20170611_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquirer',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
