# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-23 13:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_profiles', '0028_auto_20170828_0653'),
        ('tunga_profiles', '0028_auto_20170824_0025'),
    ]

    operations = [
    ]
