# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-23 13:18
from __future__ import unicode_literals

from django.db import migrations, models
import tagulous.models.fields

"""
migrations.DeleteModel(
            name='Frameworks',
        ),
        migrations.DeleteModel(
            name='Languages',
        ),
        migrations.DeleteModel(
            name='Libraries',
        ),
        migrations.DeleteModel(
            name='Platforms',
        ),
        migrations.DeleteModel(
            name='Storage',
        ),
        migrations.DeleteModel(
            name='ThirdPartyApis',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='frameworks',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='libraries',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='platforms',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='storage',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='third_party_apis',
        ),
"""


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_profiles', '0029_merge_20170923_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='type',
            field=models.CharField(choices=[(b'language', 'Language'), (b'framework', 'Framework'), (b'platform', 'Platform'), (b'library', 'Library'), (b'storage', 'Storage Engine'), (b'api', 'API'), (b'other', 'other')], default=b'other', help_text='language - Language,framework - Framework,platform - Platform,library - Library,storage - Storage Engine,api - API,other - other', max_length=30),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='skills',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, blank=True, help_text='Enter a comma-separated tag string', initial='Kampala, Entebbe, Jinja, Nairobi, Mombosa, Dar es Salaam, Kigali, Amsterdam', space_delimiter=False, to='tunga_profiles.Skill'),
        ),
    ]
