# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-04 23:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_profiles', '0030_auto_20170923_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='type',
            field=models.CharField(choices=[(b'language', 'Language'), (b'framework', 'Framework'), (b'platform', 'Platform'), (b'library', 'Library'), (b'storage', 'Storage Engine'), (b'api', 'API'), (b'other', 'Other')], default=b'other', help_text='language - Language,framework - Framework,platform - Platform,library - Library,storage - Storage Engine,api - API,other - Other', max_length=30),
        ),
    ]
