# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-19 18:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_messages', '0002_auto_20160409_2038'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='reply',
            options={'ordering': ['created_at'], 'verbose_name_plural': 'replies'},
        ),
    ]
