# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-27 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_messages', '0003_auto_20160419_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reception',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
