# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-27 12:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_messages', '0004_auto_20160427_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='status',
        ),
        migrations.RemoveField(
            model_name='reception',
            name='status',
        ),
    ]
