# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-01 05:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_messages', '0006_attachment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reply',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'replies'},
        ),
    ]
