# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-05 07:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_messages', '0009_auto_20160724_1059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channeluser',
            old_name='read_at',
            new_name='last_email_at',
        ),
    ]
