# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-25 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_messages', '0010_auto_20160805_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Direct Channel'), (2, 'Topic Channel'), (3, 'Support Channel')], default=2, help_text='1 - Direct Channel,2 - Topic Channel,3 - Support Channel'),
        ),
    ]
