# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-28 05:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_messages', '0013_auto_20160926_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='last_read',
            field=models.IntegerField(default=0),
        ),
    ]
