# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-06 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_messages', '0014_channel_last_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Direct Channel'), (2, 'Topic Channel'), (3, 'Support Channel'), (4, 'Developer Channel')], default=2, help_text='1 - Direct Channel,2 - Topic Channel,3 - Support Channel,4 - Developer Channel'),
        ),
    ]
